homepage:
    path:     /
    defaults: { _controller: Nkstamina\Controller\MainController::homepageAction }


extension:
    path:     /extension
    defaults: { _controller: Extension\Controller\ExtensionController::indexAction }