homepage:
    path:     /
    defaults: { _controller: NkStamina\NkstaminaExtension\Controller\MainController::homepageAction }


extension:
    path:     /extension/{name}
    defaults: { _controller: NkStamina\MyExtension\Controller\MyExtensionController::indexAction }